name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --no-install-recommends ca-certificates build-essential cmake git libtbb-dev libxxhash-dev
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B ./build
          cmake --build ./build --parallel
      - name: Run tests
        run: |
          ./build/recsplit_construction     -n 50k --numThreads 1 -l 8 -b 2000 --numQueries 100 --leafMethod bruteforce
          ./build/recsplit_construction     -n 50k --numThreads 4 -l 8 -b 2000 --numQueries 100 --leafMethod bruteforce
          ./build/recsplit_construction     -n 50k --numThreads 1 -l 8 -b 2000 --numQueries 100 --leafMethod rotations 
          ./build/recsplit_construction     -n 50k --numThreads 4 -l 8 -b 2000 --numQueries 100 --leafMethod rotations 
          ./build/simdrecsplit_construction -n 50k --numThreads 1 -l 8 -b 2000 --numQueries 100 --leafMethod bruteforce
          ./build/simdrecsplit_construction -n 50k --numThreads 4 -l 8 -b 2000 --numQueries 100 --leafMethod bruteforce
          ./build/simdrecsplit_construction -n 50k --numThreads 1 -l 8 -b 2000 --numQueries 100 --leafMethod rotations 
          ./build/simdrecsplit_construction -n 50k --numThreads 4 -l 8 -b 2000 --numQueries 100 --leafMethod rotations 
